### ISSUE TITLE
Missing Performance Evaluation Files in Data Modeling Directory

### ISSUE THREAD

**Issue by wei-ln** [LiqiangJing/DSBench#2]
Hi Jing,

I'm currently working on a data modeling task using your DSBench project, and I've noticed that some performance evaluation files seem to be missing. Specifically, I expected to find some Python files in the `./data_modeling/evaluation/` directory.

I've checked the following link, but it seems that the files are not present:
https://github.com/LiqiangJing/DSBench/blob/e124d87eaf44b46dc3a063c5008ad2583f6ad2ad/data_modeling/score4each_com.py#L23C1-L24C1

**Comment by LiqiangJing** [comment]
Thanks for your feedback. I have uploaded the evaluation/ directory.
