### ISSUE TITLE
 I Found a Bug in the Evaluation Script for Data Modeling Task

### ISSUE THREAD

**Issue by MrTuo** [LiqiangJing/DSBench#3]
I've encountered a bug in the evaluation script for the data modeling task(`./evaluation/covid19-global-forecasting-week-2_eval.py`). The original code at lines 22 and 24 throws a FileNotFoundError. However, when I change the code to lines 23 and 25, it works fine. This issue appears in multiple evaluation scripts.
![截屏2024-10-11 20 46 30](https://github.com/user-attachments/assets/76ff99e1-66ac-421b-9e1f-fad389a72687)

**Comment by LiqiangJing** [comment]
Thanks for your comments. We will fix it as soon as possible
