### ISSUE TITLE
Questions about the provided data files in cloud drive for data analysis task.

### ISSUE THREAD

**Issue by zimingyou01** [LiqiangJing/DSBench#4]
Hi, thanks for your valuable work!
I want to ask whether the data file provided in cloud drive (for data analysis tasks) is directly used for your evaluation in the paper or it is just raw data which needs further process for evaluation? It seems the data has some noises. And I'm not sure whether I need to organize the questions in better format according to my understanding of the paper for fair comparison.

**Comment by LiqiangJing** [comment]
I have provided the processed data in the GoogleDrive

**Comment by zimingyou01** [comment]
@LiqiangJing Thank you for your update.
